services:
  party-manager-web:
    container_name: party-manager-web
    image: party-manager-web:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:80
